mybapp/urls.py
from django.urls import include, path
from .views import *
from .views.home import home

app_name = "mybapp"

urlpatterns = [
    # User actions
    path('accounts/', include('django.contrib.auth.urls')),
    path('logout/', logout_user, name='logout'),
    path('register/', register, name="register"),
    # New user onboarding
    path('onboardings/', location_list_on, name='location_list_on'),
    path('onboarding/form', location_form_on, name='location_form_on'),
    path('firstrig/', rig_list_on, name='rig_list_on'),
    path('firstrig/form', rig_form_on, name='rig_form_on'),
    # Splash
    path('', ticket_list_s, name='home'),
    # Home
    path('home/', ticket_list_s, name='home'),
    # Lists
    path('locations/', location_list, name='location_list'),
    path('rigs/', rig_list, name='rig_list'),
    path('tickets/', ticket_list, name='ticket_list'),
    path('profiles/', profile_list, name='profile_list'),
    # Forms
    path('location/form', location_form, name='location_form'),
    path('rig/form', rig_form, name='rig_form'),
    path('ticket/form', ticket_form, name='ticket_form'),
    path('profile/form', profile_form, name='profile_form'),
    # Details
    path('locations/<int:location_id>/', location_details, name='location'),
    path('rigs/<int:rig_id>/', rig_details, name='rig'),
    path('tickets/<int:ticket_id>/', ticket_details, name='ticket'),
    path('miners/', miner_list, name='miner'),
    path('profiles/<int:profile_id>/', profile_details, name='profile'),
    # Edit forms
    path('locations/<int:location_id>/form/', location_edit_form, name='location_edit_form'),
    path('lrigs/<int:rig_id>/form/', rig_edit_form, name='rig_edit_form'),
    path('tickets/<int:ticket_id>/form/', ticket_edit_form, name='ticket_edit_form'),
    path('profiles/<int:profile_id>/form/', profile_edit_form, name='profile_edit_form'),

]

mybproject/urls.py
from django.contrib import admin
from django.urls import path, include
from mybapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mybapp.urls')),
]

mybapp/models.py
from django.db import models

# Create your models here.

mybapp/models/issue_type.py
from django.db import models
from django.shortcuts import render, redirect, reverse

class IssueType(models.Model):

    cat = models.CharField(max_length=50)

    class Meta:
        verbose_name = ("cat")
        verbose_name_plural = ("cats")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("cat_detail", kwargs={"pk": self.pk})

mybapp/models/location.py
from django.db import models
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User

class Location(models.Model):

    city = models.CharField(max_length=50)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("city")
        verbose_name_plural = ("cities")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("location_detail", kwargs={"pk": self.pk})

mybapp/models/miner.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .location import Location


class Miner(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=20)
        # Location, related_name="locations",
        # null=True, # Makes column nullable in DB
        # blank=True, # Allows blank value on objects
        # on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_miner(sender, instance, created, **kwargs):
    if created:
        Miner.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_Miner(sender, instance, **kwargs):
    instance.miner.save()

mybapp/models/rig.py
from django.db import models
from .location import Location
from .miner import Miner
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User

class Rig(models.Model):

    name = models.CharField(max_length=50)
    location = models.ForeignKey(Location, on_delete=models.CASCADE)
    # miner = models.ForeignKey(Miner, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name = ("rig")
        verbose_name_plural = ("rigs")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("rig_detail", kwargs={"pk": self.pk})

mybapp/models/ticket.py
from django.db import models
from .rig import Rig
from .issue_type import IssueType
from .miner import Miner
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import User

class Ticket(models.Model):

    title = models.CharField(max_length=50)
    comments = models.CharField(max_length=200)
    urgent = models.BooleanField(default=False)
    completed = models.BooleanField(default=False)
    category = models.ForeignKey(IssueType, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now=False, auto_now_add=True)
    rig = models.ForeignKey(Rig, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # completed = models.BooleanField(default=False)
    # miner = models.ForeignKey(Miner, on_delete=models.DO_NOTHING)
    # ****  May add the updated once I have edit functionality  ****
    # updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = ("ticket")
        verbose_name_plural = ("tickets")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ticket_detail", kwargs={"pk": self.pk})

mybapp/forms/register_form.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    # first_name = forms.CharField(max_length=30, required=False, help_text='')
    username = forms.CharField(max_length=30, required=False, help_text='*')
    email = forms.EmailField(max_length=254, help_text='*')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

mybapp/views.py
from django.shortcuts import render

# Create your views here.

mybapp/views/connection.py
class Connection:
    db_path = "/Users/juliangarcia/mine-your-business/mybproject/db.sqlite3"

mybapp/views/home.py
from django.shortcuts import render
from ..views.tickets.list import Ticket
from django.contrib.auth.decorators import login_required
from .connection import Connection


# @login_required
def ticket_list_s(request):
    if request.method == 'GET':
        with sqlite3.connect(Connection.db_path) as conn:
            current_user = request.user
            conn.row_factory = sqlite3.Row
            db_cursor = conn.cursor()

            db_cursor.execute("""
            select
                t.id,
                t.title,
                t.comments,
                t.urgent,
                t.created_at,
                i.cat,
                r.name,
                t.user_id
                
            from mybapp_ticket t
            JOIN mybapp_issuetype i
            ON t.category_id = i.id
            JOIN mybapp_rig r 
            ON r.id = t.rig_id
            WHERE t.user_id = ? AND urgent = 1
            ORDER BY created_at ASC
            LIMIT 3
            """, (current_user.id,))

            all_tickets = []
            dataset = db_cursor.fetchall()

            for row in dataset:
                ticket = Ticket()
                ticket.id = row['id']
                ticket.title = row['title']
                ticket.comments = row['comments']
                ticket.urgent = row['urgent']
                ticket.created_at = row['created_at']
                ticket.cat= row['cat']
                ticket.name = row['name']
                ticket.user_id = row['user_id']
                # *** Might bring this back ***
                # ticket.completed = row['completed']
                # ticket.miner_id = row['miner_id']
                # print('I am ticket', ticket.issue_type_name)

                all_tickets.append(ticket)

        template = 'home/home.html'
        context = {
            'all_tickets': all_tickets
        }

        return render(request, template, context)

@login_required
def home(request):
    if request.method == 'GET':
        template = 'home/home.html'
        context = {}

        return render(request, template, context)

mybapp/templates/first_rigs/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" c
    ontent="width=device-width, 
    initial-scale=1, 
    shrink-to-fit=no">

    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'styles/onboarding-1.css' %}" />

    <title>MYB</title>
  </head>
  <body>
  <div class="card-loc">
    <center><h1 class="display-3">Lets make your first Rig!</h1></center>

    {% if rig.id is not None %}
        <form action="{% url 'mybapp:rig' rig.id %}" method="post">
    {% else %}
        <form action="{% url 'mybapp:rig_list_on' %}" method="post">
    {% endif %}
        {% csrf_token %}

    <center><form action="{% url 'mybapp:rig_list_on' %}" method="post">
      {% csrf_token %}
      <fieldset class="display-4">
          <label for="location">location: </label>
          <button class="btn btn-light btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <select 
          id="location" 
          type="text" 
          name="location">
                {% for location in all_locations %}
                    <option {% if location.id == rig.location_id %}selected{% endif %} value="{{ location.id }}">
                    {{ location.city }}</option>
                {% endfor %}
          </select>
          </button>
          <br>
          <button class="btn-warning btn-lg"><a href='http://localhost:8000/onboarding/form'>Create a Location</a></button>
      </fieldset>
      <fieldset>
          <label for="name" class="display-4">name: </label>
          <input id="name" type="text" class="form-control form-control-lg city-input" name="name" value="{{ rig.name }}">
      </fieldset>
      <br>

      {% if rig.id is not None %}
          <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
      {% else %}
          <button class="btn-warning btn-lg"><input type="submit" value="Create" /></button>
      {% endif %}
    </form></center>
  </body>
  </div>
</html>

mybapp/templates/locations/detail.html
{% extends 'shared/base.html' %}
{% block content %}
{% load static %}
<div>
    <center><div>
        <h3></h3>
        <h3> {{ location.city }}</h3>
        <br>
        <section>
            <form action="{% url 'mybapp:location' location.id %}" method="POST">
                {% csrf_token %}
                <input type="hidden" name="actual_method" value="DELETE">
            <button class="btn btn-warning">Remove!</button>
            </form>
            <br>
            <form action="{% url 'mybapp:location_edit_form' location.id %}" method="GET">
                {% csrf_token %}
                <button class="btn btn-warning">Edit</button>
            </form>
        </section>
    </div></center>
    <br>
    <ul>
    <p>Rigs in {{ location.city }}<p/>
    {% for rig in rigs %}
        <li>
            {{ rig.name }}
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}

mybapp/templates/locations/form.html
{% extends 'shared/base.html' %}

{% block content %}

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MYB</title>

    <link rel="stylesheet" href="{% static 'styles/form.css' %}" />
  </head>
  <body>
  <center><div>
    <h1 class="title-location-form">Location Form</h1>

    {% if location.id is not None %}
        <form action="{% url 'mybapp:location' location.id %}" method="post">
    {% else %}
        <form action="{% url 'mybapp:location_list' %}" method="post">
    {% endif %}
        {% csrf_token %}

    {% comment %} <form action="{% url 'mybapp:location_list' %}" method="post"> {% endcomment %}
      {% csrf_token %}
      
      <fieldset>
          <label for="city">city: </label>
          <input class="city-input" id="city" type="text" name="city" value="{{ location.city }}">
      </fieldset>
      <br>
      {% if location.id is not None %}
          <input type="hidden" name="actual_method" value="PUT">
            <center><button class="btn-warning btn-lg"><input type="submit" value="Update" /></button></center>
      {% else %}
          <center><button class="btn-warning btn-lg"><input type="submit" value="Create" /></button></center>
      {% endif %}
    </form>
  </div></center>
  </body>
</html>

{% endblock %}

mybapp/templates/locations/list.html
{% extends 'shared/base.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mine Your Business</title>
  </head>
  <body>
  <center><img class="logo" src="../../static/img/slide-7.svg" width="30%"></img></center>
  <center><div>
    <h1>locations</h1>
        <button class="btn btn-warning"><a class="text-white" href="{% url 'mybapp:location_form' %}">Add Location</a></button>
    <br>
    <br>
    <p>View your rigs by location</p>
    {% comment %} <ul> {% endcomment %}
    {% for location in all_locations %}
        <div>
            {% comment %} {{ location.city }} {% endcomment %}
            <button class="btn btn-secondary"><a class="text-white" href="{% url 'mybapp:location' location.id %}">{{ location.city }}<a/></button>
        </div>
        <br>
    {% endfor %}
    {% comment %} </ul> {% endcomment %}
  <div></center>
  </body>
</html>
{% endblock %}

mybapp/templates/miners/list.html
{% extends 'shared/base.html' %}

{% block content %}

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mine Your Business</title>
  </head>
  <body>
    <h1>Fellow Miners</h1>

    <ol>
    {% for miner in all_miners %}
        <li>
            {{ miner.username }}
            : {{miner.email}}
        </li>
    {% endfor %}
    </ol>
  </body>
</html>
{% endblock %}

mybapp/templates/onboardings/form.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" c
    ontent="width=device-width, 
    initial-scale=1, 
    shrink-to-fit=no">

    <link rel="stylesheet" 
    href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'styles/onboarding-1.css' %}" />

    <title>MYB</title>
  </head>
  <body>
    <div class="card-loc">
      <center><h1 class="display-3">Let's get started!</h1></center>

      {% if location.id is not None %}
          <form action="{% url 'mybapp:location' location.id %}" method="post">
      {% else %}
          <form action="{% url 'mybapp:location_list_on' %}" method="post">
      {% endif %}
          {% csrf_token %}

      <form action="{% url 'mybapp:location_list_on' %}" method="post">
        {% csrf_token %}
        <br>
        <br>
        <center><p class="display-4">Where's your current miner?</p></center>
        <fieldset>
          <div class="form-group">
            <center><label 
            for="exampleInputPassword1 city">
            City:
            </label></center>
            <center><input 
            type="text" 
            name="city" 
            class="form-control form-control-lg city-input" 
            id="exampleInputPassword1 city" 
            value="{{ location.city }}"></center>
          </div>
            {% comment %} <label for="city">city: </label>
            <input id="city" type="text" name="city" value="{{ location.city }}"> {% endcomment %}
        </fieldset>

        {% if location.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
              <input type="submit" value="Update" />
        {% else %}
            <button class="create-location-button"><input type="submit" class="btn btn-warning btn-lg" value="Create" /></button>
        {% endif %}
      </form>
    </div>
  </body>
</html>

mybapp/templates/profiles/detail.html
{% extends 'shared/base.html' %}
{% block content %}
{% load static %}

<link rel="stylesheet" href="{% static 'styles/details.css' %}" />

<center><div class="title-profile-details">
    <h3>Profile</h3>
    <h3> {{ profile.username }}</h3>
    <h3> {{ profile.email }}</h3>
    <h3> {{ profile.city }}</h3>
    <section>
        <br>
        {% comment %} This is a stretch goal {% endcomment %}
        {% comment %} <form action="{% url 'mybapp:profile' profile.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
        <button class="btn-warning btn-lg">Remove!</button>
        </form> {% endcomment %}
        <br>
        <form action="{% url 'mybapp:profile_edit_form' profile.id %}" method="GET">
            {% csrf_token %}
            <button class="btn-warning btn-lg">Edit</button>
        </form>
    </section>
</div></center>

    {% comment %} <ul>
    <p>Rigs in this profile<p/>
    {% for rig in rigs %}
        <li>
            {{ rig.name }}
        </li>
    {% endfor %}
    </ul> {% endcomment %}
    
{% endblock %}

mybapp/templates/profiles/form.html
{% extends 'shared/base.html' %}

{% block content %}

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MYB</title>

    <link rel="stylesheet" href="{% static 'styles/form.css' %}" />
  </head>
  <body>
  
    <center><h1>Profile Form</h1></center>

     <center>
    {% if profile.id is not None %}
        <form action="{% url 'mybapp:profile' profile.id %}" method="post">
    {% else %}
        <form action="{% url 'mybapp:profile_list' %}" method="post">
    {% endif %}
        {% csrf_token %}

    {% comment %} <form action="{% url 'mybapp:profile_list' %}" method="post"> {% endcomment %}
      {% comment %} {% csrf_token %} {% endcomment %}

      <fieldset>
          <label for="email">Email </label>
          <input class="form-control form-control-lg profile-input" id="email" type="email" name="email" value="{{ profile.email }}">
      </fieldset>
      <br>
      <fieldset>
          <label for="email">Your city </label>
          <input class="form-control form-control-lg profile-input" id="city" type="text" name="city" value="{{ profile.city }}">
      </fieldset>
      <br>

      {% if profile.id is not None %}
      <button class="btn-warning btn-md">
          <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
            </button>
      {% else %}
      <button class="btn-warning btn-md">
          <input type="submit" value="Create" />
          </button>
      {% endif %}
    </form>
    </center>

  </body>
</html>

{% endblock %}

mybapp/templates/profiles/list.html
{% extends 'shared/base.html' %}

{% block content %}
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mine Your Business</title>
  </head>
  <body>
    <br>
    <br>
    <center><img class="logo" src="../../static/img/slide-8.svg" width="50%"></img></center>

    {% for profile in current_profile %}
    <center>
    <div>
    <h3>Welcome, {{ profile.username }}. What would you like to do?</h3>
        {% comment %} <button><a href="{% url 'mybapp:profile_form' %}">Add Location</a></button> {% endcomment %}
            <br>
    <div>
            <button class="btn-warning btn-lg"><a class="text-white" href="{% url 'mybapp:profile' profile.id %}">View details<a/></button>
            <br>
            <br>
            <button class="btn-warning btn-lg"><a class="text-white" href="{% url 'mybapp:logout' %}">Logout<a/></button>
            {% comment %} {{ profile.username }}  {% endcomment %}
            {% comment %} <br>
            {{ profile.email }} 
            <br>
            {{ profile.city }} {% endcomment %}
    {% endfor %}
    </div>
    </div></center>
  </body>
</html>
{% endblock %}

mybapp/templates/rigs/detail.html
{% extends 'shared/base.html' %}

{% block content %}

{% load static %}

<link rel="stylesheet" href="{% static 'styles/details.css' %}" />

<center><div class="title-rig-details">
    <h1> Rig Details</h1>
    <br>
    <h4>Name: {{ rig.name }}</h4>
    <h4>Location: {{ rig.city }}</h4>
    <br>
    <br>
    <section>
        <form action="{% url 'mybapp:rig' rig.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
        <center><button class="btn-warning btn-lg">Remove</button></center>
        </form>
        <br>
        <form action="{% url 'mybapp:rig_edit_form' rig.id %}" method="GET">
            {% csrf_token %}
            <center><button class="btn-warning btn-lg">Edit</button></center>
        </form>
    </section>
</div></center>
    
{% endblock %}

mybapp/templates/rigs/form.html
{% extends 'shared/base.html' %}

{% block content %}

{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>MYB</title>

    <link rel="stylesheet" href="{% static 'styles/form.css' %}" />
  </head>
  <body>
    <center><h1>Rig Form</h1></center>

    {% if rig.id is not None %}
        <form action="{% url 'mybapp:rig' rig.id %}" method="post">
    {% else %}
        <form action="{% url 'mybapp:rig_list' %}" method="post">
    {% endif %}
        {% csrf_token %}

    <center><form action="{% url 'mybapp:rig_list' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="location">location: </label>
          <br>
          <button 
          class="btn btn-light btn-lg dropdown-toggle" 
          type="button" 
          data-toggle="dropdown" 
          aria-haspopup="true" 
          aria-expanded="false">
            <select 
            id="location" 
            type="text" 
            name="location">
                {% for location in all_locations %}
                    <option {% if location.id == rig.location_id %}selected{% endif %} value="{{ location.id }}">
                    {{ location.city }}</option>
                {% endfor %}
            </select>
          </button>
          <br>
          <br>
          <center><button class="btn-warning btn-md">
            <a class="text-white" href='http://localhost:8000/location/form'>Create a Location</a>
          </center></button>
      </fieldset>
      <fieldset>
          <label for="name">name: </label>
          <input class="form-control form-control-lg city-input" id="name" type="text" name="name" value="{{ rig.name }}">
      </fieldset>
      <br>

      {% if rig.id is not None %}
      <button class="btn-warning btn-md">
          <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
      </button>
      {% else %}
        <button class="btn-warning btn-md">
          <input class="text-white" type="submit" value="Create" />
        </button>
      {% endif %}
    </form></center>
  </body>
</html>

{% endblock %}

mybapp/templates/rigs/list.html
{% extends 'shared/base.html' %}

{% block content %}
{% load static %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Mine Your Business</title>
  </head>
  <center><img class="logo" src="../../static/img/slide-6.svg" width="30%"></img></center>
  <body>
    <center><h1>Rigs</h1></center>
        <center><button class="btn btn-warning"><a class="text-white" href="{% url 'mybapp:rig_form' %}">Add Rig</a></button></center>
    {% comment %} <ol> {% endcomment %}
    <br>
    
    {% for rig in all_rigs %}
        <div>
          {% comment %} <h5 class="card-header p-3 mb-2 bg-secondary text-white">{{ ticket.title }}</h5> {% endcomment %}
            <h5 class="card-header p-3 mb-2 bg-secondary text-white"><a class="text-white" href="{% url 'mybapp:rig' rig.id %}">{{ rig.name }}<a/></h5>
            {% comment %} Rig: {{ rig.name }} {% endcomment %}
            {% comment %} <br> {% endcomment %}
            Location: {{rig.city}}
            <br>
            <br>
        </div>
    {% endfor %}
    {% comment %} </ol> {% endcomment %}
  </body>
</html>

{% endblock %}

mybapp/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Mine Your Business</title>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" 
    integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" 
    crossorigin="anonymous">

    {% block css %}
    {% endblock %}
</head>

<body>

    <div class="pos-f-t sticky-top">
    <div class="collapse" id="navbarToggleExternalContent">
        <div class="bg-dark p-4">
        <h5 class="text-white h4">MYB Menu</h5>
        {% comment %} <span class="text-muted">Toggleable via the navbar brand.</span> {% endcomment %}
        <li class="navList__route"><a href="{% url 'mybapp:ticket_list' %}">Tickets</a></li>
        <li class="navList__route"><a href="{% url 'mybapp:rig_list' %}">Rigs</a></li>
        <li class="navList__route"><a href="{% url 'mybapp:home' %}">Home</a></li>
        <li class="navList__route"><a href="{% url 'mybapp:location_list' %}">Locations</a></li>
        <li class="navList__route"><a href="{% url 'mybapp:profile_list' %}">Profile</a></li>
        </div>
    </div>
    <nav class="navbar navbar-dark bg-dark">
        <button class="navbar-toggler" 
        type="button" 
        data-toggle="collapse" 
        data-target="#navbarToggleExternalContent" 
        aria-controls="navbarToggleExternalContent" 
        aria-expanded="false" 
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon">
        </span>
        </button>
    </nav>
    </div>
    {% comment %} <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'mybapp:ticket_list' %}">Tickets</a></li>
            <li class="navList__route"><a href="{% url 'mybapp:rig_list' %}">Rigs</a></li>
            <li class="navList__route"><a href="{% url 'mybapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'mybapp:location_list' %}">Locations</a></li>
            <li class="navList__route"><a href="{% url 'mybapp:profile_list' %}">Profile</a></li>
        </ol>
    </nav> {% endcomment %}

{% comment %} <center><h1>MYB</h1></center> {% endcomment %}

    {% block content %}
    {% endblock %}

    {% comment %} {% block scripts %} {% endcomment %}
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% comment %} {% endblock scripts %} {% endcomment %}

</body>

</html>